export const platforms = [
  {
    platform_id: "1",
    platform_name: "NES",
  },
  {
    platform_id: "2",
    platform_name: "SNES",
  },
  {
    platform_id: "3",
    platform_name: "Gameboy",
  },
  {
    platform_id: "4",
    platform_name: "PS1",
  },
  {
    platform_id: "5",
    platform_name: "N64",
  },
  {
    platform_id: "6",
    platform_name: "GBC",
  },
  {
    platform_id: "7",
    platform_name: "PS2",
  },
  {
    platform_id: "8",
    platform_name: "Gamecube",
  },
  {
    platform_id: "9",
    platform_name: "GBA",
  },
  {
    platform_id: "10",
    platform_name: "DS",
  },
  {
    platform_id: "11",
    platform_name: "PS3",
  },
  {
    platform_id: "12",
    platform_name: "Wii",
  },
  {
    platform_id: "13",
    platform_name: "3DS",
  },
  {
    platform_id: "14",
    platform_name: "Wii U",
  },
  {
    platform_id: "15",
    platform_name: "PS4",
  },
  {
    platform_id: "16",
    platform_name: "Switch",
  },
  {
    platform_id: "17",
    platform_name: "PS5",
  },
  {
    platform_id: "18",
    platform_name: "Switch 2",
  },
  {
    platform_id: "100",
    platform_name: "PC",
  },
];

export const games = [
  {
    platform_id: "1",
    name: "Super Mario Bros.",
    licence: "Nintendo Switch Online",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: null,
    hltb_time: "2",
    tried: "1",
    finished: "1",
    rating: "7.5",
    when_played: "2023-08-27",
  },
  {
    platform_id: "1",
    name: "Super Mario Bros. 2",
    licence: "Nintendo Switch Online",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario Bros.",
    hltb_time: "3.5",
    tried: "1",
    finished: "1",
    rating: "6",
    when_played: "2023-09-03",
  },
  {
    platform_id: "1",
    name: "Super Mario Bros. 3",
    licence: "Nintendo Switch Online",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario Bros. 2",
    hltb_time: "6",
    tried: "1",
    finished: "0",
    rating: "5",
    when_played: "2024-06-16",
  },
  {
    platform_id: "2",
    name: "Super Mario World",
    licence: "Nintendo Switch Online",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario Bros. 3",
    hltb_time: "7.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "3",
    name: "Super Mario Land",
    licence: "Nintendo Switch Online",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario Bros. 3",
    hltb_time: "1",
    tried: "1",
    finished: "1",
    rating: "6",
    when_played: "2024-07-01",
  },
  {
    platform_id: "3",
    name: "Super Mario Land 2: 6 Golden Coins",
    licence: "Nintendo Switch Online",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario Land",
    hltb_time: "3",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "5",
    name: "Super Mario 64",
    licence: "Switch Cartridge (remake)",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario World",
    hltb_time: "17",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "8",
    name: "Super Mario Sunshine",
    licence: "Switch Cartridge (remake)",
    play_method: "Switch",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario 64",
    hltb_time: "20",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "9",
    name: "Pokemon Emerald",
    licence: "GBA Cartridge",
    play_method: "GBA",
    retro: "1",
    handheld: "1",
    prequel_name: "Pokemon Emerald",
    hltb_time: "65.5",
    tried: "1",
    finished: "1",
    rating: "7.5",
    when_played: "2024-11-23",
  },
  {
    platform_id: "9",
    name: "Pokemon LeafGreen",
    licence: "GBA Cartridge",
    play_method: "GBA",
    retro: "1",
    handheld: "1",
    prequel_name: null,
    hltb_time: "29.5",
    tried: "1",
    finished: "1",
    rating: "7",
    when_played: "2023-09-12",
  },
  {
    platform_id: "10",
    name: "New Super Mario Bros.",
    licence: "ROM",
    play_method: "DS",
    retro: "1",
    handheld: "1",
    prequel_name: "Super Mario World",
    hltb_time: "11",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "10",
    name: "Pokemon Black",
    licence: "DS Cartridge",
    play_method: "DS",
    retro: "1",
    handheld: "1",
    prequel_name: "Pokemon Heartgold",
    hltb_time: "61.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "10",
    name: "Pokemon HeartGold",
    licence: "DS Cartridge",
    play_method: "DS",
    retro: "1",
    handheld: "1",
    prequel_name: "Pokemon Platinum",
    hltb_time: "72.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "10",
    name: "Pokemon Platinum",
    licence: "DS Cartridge",
    play_method: "DS",
    retro: "1",
    handheld: "1",
    prequel_name: "Pokemon Emerald",
    hltb_time: "69",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "10",
    name: "Pokemon White 2",
    licence: "DS Cartridge",
    play_method: "DS",
    retro: "1",
    handheld: "1",
    prequel_name: "Pokemon Black",
    hltb_time: "64.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "12",
    name: "New Super Mario Bros. Wii",
    licence: "ROM",
    play_method: "Wii U",
    retro: "1",
    handheld: "0",
    prequel_name: "New Super Mario Bros.",
    hltb_time: "13.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "12",
    name: "Super Mario Galaxy",
    licence: "Switch Cartridge (remake)",
    play_method: "Switch",
    retro: "0",
    handheld: "0",
    prequel_name: "Super Mario Sunshine",
    hltb_time: "21.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "12",
    name: "Super Mario Galaxy 2",
    licence: "Wii Disc",
    play_method: "Wii U",
    retro: "1",
    handheld: "0",
    prequel_name: "Super Mario Galaxy",
    hltb_time: "21",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Black Mesa",
    licence: "PC Download",
    play_method: "PC",
    retro: "1",
    handheld: "0",
    prequel_name: null,
    hltb_time: "18",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Half-Life 2",
    licence: "PC Download",
    play_method: "PC",
    retro: "1",
    handheld: "0",
    prequel_name: "Black Mesa",
    hltb_time: "15.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Half-Life 2: Episode One",
    licence: "PC Download",
    play_method: "PC",
    retro: "1",
    handheld: "0",
    prequel_name: "Half-Life 2",
    hltb_time: "4",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Half-Life 2: Episode Two",
    licence: "PC Download",
    play_method: "PC",
    retro: "1",
    handheld: "0",
    prequel_name: "Half-Life 2: Episode One",
    hltb_time: "6",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Mass Effect",
    licence: "PC Download",
    play_method: "PC",
    retro: "1",
    handheld: "0",
    prequel_name: null,
    hltb_time: "27.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Octopath Traveler",
    licence: "ROM",
    play_method: "PC",
    retro: "0",
    handheld: "0",
    prequel_name: null,
    hltb_time: "80.5",
    tried: null,
    finished: null,
    rating: null,
    when_played: null,
  },
  {
    platform_id: "100",
    name: "Slay The Spire",
    licence: "PC Download",
    play_method: "PC",
    retro: "0",
    handheld: "0",
    prequel_name: null,
    hltb_time: "47",
    tried: "1",
    finished: "0",
    rating: "8.5",
    when_played: "2024-08-21",
  },
];
